#!/usr/bin/env bash
# Pre-commit hook script — ensures every staged source file has a license
# header before the commit is recorded. Generated by /vibe-ops:license-setup;
# generalized from a scheme first built for a fork-with-dual-attribution case
# — edit the glob below if this repo's source files use other extensions.
#
# Header format: SPDX identifier only, no per-file copyright line. Per ASF's
# own current practice (apache.org/legal/src-headers.html), a copyright line
# on every file is not recommended — it goes stale the moment someone else
# touches the file. Copyright is tracked collectively in NOTICE + AUTHORS.
#
# The script re-stages files it modifies so the header lands in the same commit.
set -euo pipefail

SOURCE_GLOBS=({{SOURCE_GLOB_ARRAY}})
LICENSE_HEADER='// SPDX-License-Identifier: {{LICENSE_ID}}'
HEADER_MARKER='SPDX-License-Identifier|Copyright'

<!-- FORK_ONLY:start -->
MIXED_HEADER='// SPDX-License-Identifier: {{LICENSE_ID}} AND {{ORIGIN_LICENSE_SHORT}}
// Portions from {{ORIGIN_PROJECT}} ({{ORIGIN_AUTHOR}}) — see NOTICE'
<!-- FORK_ONLY:end -->

# --check mode (used by CI): verify every tracked source file carries a
# license header (either the new SPDX form or an old grandfathered block).
# Read-only — never modifies files; exits 1 if any lack one. Independent of
# the local hook so `--no-verify` / a missing hook can't merge unlicensed code.
if [[ "${1:-}" == "--check" ]]; then
  missing=0
  while IFS= read -r f; do
    [[ -z "$f" || ! -f "$f" ]] && continue
    if ! head -10 "$f" | grep -qE "$HEADER_MARKER"; then
      echo "  [license:MISSING] $f"
      missing=$((missing + 1))
    fi
  done <<< "$(git ls-files -- "${SOURCE_GLOBS[@]}")"
  if [[ $missing -gt 0 ]]; then
    echo "ERROR: $missing file(s) missing a license header. Commit locally (the"
    echo "pre-commit hook injects it) or add the header manually."
    exit 1
  fi
  echo "License header check passed."
  exit 0
fi

STAGED=$(git diff --cached --name-only --diff-filter=ACMR -- "${SOURCE_GLOBS[@]}" 2>/dev/null || true)

if [[ -z "$STAGED" ]]; then
  exit 0
fi

injected=0

while IFS= read -r f; do
  [[ -z "$f" || ! -f "$f" ]] && continue

  # Already headered → nothing to do
  if head -5 "$f" | grep -q "SPDX-License-Identifier"; then
    continue
  fi

  # Defaults for the plain (non-fork) case; the fork-only block below
  # overrides these when an old dual-license header needs classifying.
  old_header_end=""
  header="$LICENSE_HEADER"
  kind="plain"

<!-- FORK_ONLY:start -->
  # Detect an old-style leading prose-block header (`/*` on line 1, closing
  # ` */` further down, "Copyright" somewhere inside) so it can be replaced
  # rather than stacked underneath the new SPDX line.
  old_header_is_mixed=0
  old_header_is_pure_legacy=0
  if [[ "$(sed -n '1p' "$f")" == "/*" ]]; then
    old_header_end=$(awk '/^ \*\/$/{print NR; exit}' "$f")
    if [[ -n "$old_header_end" ]]; then
      old_block="$(sed -n "1,${old_header_end}p" "$f")"
      if ! grep -q "Copyright" <<< "$old_block"; then
        old_header_end=""
      elif grep -q "{{ORIGIN_LICENSE_SHORT}}" <<< "$old_block"; then
        if grep -qE "{{LICENSE_ID}}|{{PROJECT_NAME}}" <<< "$old_block"; then
          old_header_is_mixed=1
        else
          # Origin license mentioned, but no project marker: this file was
          # never actually modified by the project. Don't relicense it —
          # leave its header exactly as-is.
          old_header_is_pure_legacy=1
        fi
      fi
    fi
  fi

  if [[ "$old_header_is_pure_legacy" -eq 1 ]]; then
    continue
  fi

  if [[ -n "$old_header_end" && "$old_header_is_mixed" -eq 1 ]]; then
    header="$MIXED_HEADER"
    kind="mixed"
  fi
<!-- FORK_ONLY:end -->

  tmpfile="$(mktemp)"
  printf '%s\n\n' "$header" > "$tmpfile"

  if [[ -n "$old_header_end" ]]; then
    body_start=$((old_header_end + 1))
    # also swallow one blank line right after the old block, if present
    if [[ -z "$(sed -n "${body_start}p" "$f")" ]]; then
      body_start=$((body_start + 1))
    fi
    sed -n "${body_start},\$p" "$f" >> "$tmpfile"
    action="migrated"
  else
    cat "$f" >> "$tmpfile"
    action="injected"
  fi

  mv "$tmpfile" "$f"
  git add "$f"

  echo "  [license:$kind:$action] $f"
  injected=$((injected + 1))
done <<< "$STAGED"

if [[ $injected -gt 0 ]]; then
  echo "License headers processed for $injected file(s)."
fi
